---
- name: Configure web server via SSM
  hosts: web
  gather_facts: false
  vars:
    ansible_connection: aws_ssm

  tasks:
    - name: Install nginx
      ansible.builtin.shell: |
        dnf -y install nginx
        systemctl enable --now nginx
      register: install_out
      changed_when: "'Complete!' in install_out.stdout or 'installed' in install_out.stdout"

    - name: Create simple index.html
      ansible.builtin.copy:
        dest: /usr/share/nginx/html/index.html
        content: |
          <html>
            <head><title>Success!</title></head>
            <body>
              <h1>Hello from Ansible + SSM 🎉</h1>
            </body>
          </html>
        owner: root
        group: root
        mode: '0644'

    - name: Check nginx is running
      ansible.builtin.shell: systemctl is-active nginx
      register: nginx_status
      failed_when: nginx_status.stdout.strip() != "active"

